# Assignment 5

In [1]:
import numpy as np

## Q1: NumPy 1D Array — Basic Operations

Write a program to create a NumPy 1D-array with 5 elements and perform basic operations like:

**a)** Addition of 2 to all the elements  
**b)** Multiplication of 3 with all the elements  
**c)** Divide every element by 2 

In [2]:
arr = np.array([1, 2, 3, 4, 5])
print("Original array:", arr)
add_result = arr + 2
print("After adding 2:", add_result)
mul_result = arr * 3
print("After multiplying by 3:", mul_result)
divide_by_2 = arr / 2
print("After division: ", divide_by_2)

Original array: [1 2 3 4 5]
After adding 2: [3 4 5 6 7]
After multiplying by 3: [ 3  6  9 12 15]
After division:  [0.5 1.  1.5 2.  2.5]


## Q2: Questions on Basic NumPy Array

**a)** Reverse the NumPy array:  
`arr = np.array([1, 2, 3, 6, 4, 5])`

**b)** Find the most frequent value and their indice(s) in the following arrays:  
&nbsp;&nbsp;&nbsp;&nbsp;i. `x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])`  
&nbsp;&nbsp;&nbsp;&nbsp;ii. `y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])`

In [3]:
arr = np.array([1, 2, 3, 6, 4, 5])
reversed_arr = arr[::-1]
print("Reversed array:", reversed_arr)
def most_frequent(arr):
    values, counts = np.unique(arr, return_counts=True)
    max_count = counts.max()
    most_frequent_values = values[counts == max_count]
    indices = np.where(np.isin(arr, most_frequent_values))[0]
    return most_frequent_values, indices

x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])

x_val, x_idx = most_frequent(x)
print("x -> Most frequent value(s):", x_val, "at indices:", x_idx)

y_val, y_idx = most_frequent(y)
print("y -> Most frequent value(s):", y_val, "at indices:", y_idx)

Reversed array: [5 4 6 3 2 1]
x -> Most frequent value(s): [1] at indices: [0 5 7 8 9]
y -> Most frequent value(s): [1 3] at indices: [0 1 2 4 8 9]


## Q3: Accessing Elements in a 2-D Array

For the given 2-D array:  
`arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])`

Access elements using row and column indices as follows:

**a)** Access 1st row, 2nd column  
**b)** Access 3rd row, 1st column

In [4]:
arr = np.array([[10, 20, 30],
                 [40, 50, 60],
                 [70, 80, 90]])
print("Array:\n", arr)
print("1st row, 2nd column:", arr[0, 1])
print("3rd row, 1st column:", arr[2, 0])

Array:
 [[10 20 30]
 [40 50 60]
 [70 80 90]]
1st row, 2nd column: 20
3rd row, 1st column: 70


## Q.4  Write program to create an 1-D NumPy array named <<Your Name>> with evenly spaced 25 numbers from 10 to 100 using linspace(). Print the dimensions of the array, shape, total elements, the data type of each element and total number of bytes consumed by the array. Find the transpose of this array using reshape() attribute. Can we do the same with T attribute?

In [5]:
Kanan = np.linspace(10, 100, 25)
print("Array:", Kanan)
# Dimensions, shape, size, dtype, bytes
print("\nDimensions (ndim):", Kanan.ndim)
print("Shape:", Kanan.shape)
print("Total elements (size):", Kanan.size)
print("Data type (dtype):", Kanan.dtype)
print("Total bytes consumed (nbytes):", Kanan.nbytes)
# Transpose using reshape()
Kanan_reshaped = Kanan.reshape(25, 1)
print("\nTransposed using reshape(25,1):\n", Kanan_reshaped)
# Transpose using T attribute
Kanan_T = Kanan.T
print("\nTransposed using .T attribute:\n", Kanan_T)
print("Shape after .T:", Kanan_T.shape)

Array: [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]

Dimensions (ndim): 1
Shape: (25,)
Total elements (size): 25
Data type (dtype): float64
Total bytes consumed (nbytes): 200

Transposed using reshape(25,1):
 [[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]

Transposed using .T attribute:
 [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Shape after .T: (25,)


## Q5. Create a 2-D Array of three rows and four columns, named ucs420_<<your_name>> with following values – 10, 20, 30, 40, 50, 60, 70, 80, 90, 15, 20, 35. Compute the mean, median, max, min, unique elements. Reshape the array to four rows and three columns and name it as reshaped_ ucs420_<<your_name>>. Resize the array to two rows and three columns and name it as resized_ ucs420_<<your_name>>.

In [6]:
ucs420_kanan = np.array([[10, 20, 30, 40],
                          [50, 60, 70, 80],
                          [90, 15, 20, 35]])
print("ucs420_kanan:\n", ucs420_kanan)
print("\nMean:", np.mean(ucs420_kanan))
print("Median:", np.median(ucs420_kanan))
print("Max:", np.max(ucs420_kanan))
print("Min:", np.min(ucs420_kanan))
print("Unique elements:", np.unique(ucs420_kanan))
reshaped_ucs420_kanan = ucs420_kanan.reshape(4, 3)
print("\nreshaped_ucs420_kanan:\n", reshaped_ucs420_kanan)
resized_ucs420_kanan = np.resize(ucs420_kanan, (2, 3))
print("\nresized_ucs420_kanan:\n", resized_ucs420_kanan)

ucs420_kanan:
 [[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]

Mean: 43.333333333333336
Median: 37.5
Max: 90
Min: 10
Unique elements: [10 15 20 30 35 40 50 60 70 80 90]

reshaped_ucs420_kanan:
 [[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]

resized_ucs420_kanan:
 [[10 20 30]
 [40 50 60]]
